SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

FPS = 60

PLAYER_IMAGE_PATH = "player_image.png"
PLAYER_WIDTH = 30
PLAYER_HEIGHT = 40
PLAYER_SPEED = 5
PLAYER_GRAVITY = 0.5
PLAYER_JUMP_STRENGTH = -12
PLAYER_MAX_FALL_SPEED = 10

TILE_SIZE = 40

STAR_IMAGE_PATH = "star_image.png"

UI_FONT_PATH = "FancyFont.ttf"
# HEART_IMAGE_PATH = "heart.png" # Nebenaudojama PuzzleLevel
